/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_adaptinet_sdk_fastcache_DataItem */

#ifndef _Included_org_adaptinet_sdk_fastcache_DataItem
#define _Included_org_adaptinet_sdk_fastcache_DataItem
#ifdef __cplusplus
extern "C" {
#endif
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMEMPTY
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMEMPTY 0L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMNULL
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMNULL 1L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMI2
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMI2 2L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMI4
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMI4 3L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMR4
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMR4 4L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMR8
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMR8 5L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMDATE
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMDATE 7L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMSSTR
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMSSTR 8L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMERROR
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMERROR 10L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMBOOL
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMBOOL 11L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMDATAITEM
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMDATAITEM 12L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMDECIMAL
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMDECIMAL 14L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMI1
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMI1 16L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMUI1
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMUI1 17L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMUI2
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMUI2 18L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMUI4
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMUI4 19L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMI8
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMI8 20L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMUI8
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMUI8 21L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMINT
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMINT 22L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMUINT
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMUINT 23L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMVOID
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMVOID 24L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMLONG
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMLONG 25L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMPTR
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMPTR 26L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMLPSTR
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMLPSTR 30L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMINT_PTR
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMINT_PTR 37L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMUINT_PTR
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMUINT_PTR 38L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMLONG_PTR
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMLONG_PTR 39L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMDOUBLE_PTR
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMDOUBLE_PTR 64L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMVECTOR
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMVECTOR 4096L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMARRAY
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMARRAY 8192L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMBYREF
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMBYREF 16384L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMRESERVED
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMRESERVED 32768L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMILLEGAL
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMILLEGAL 65535L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMILLEGALMASKED
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMILLEGALMASKED 4095L
#undef org_adaptinet_sdk_fastcache_DataItem_DATAITEMTYPEMASK
#define org_adaptinet_sdk_fastcache_DataItem_DATAITEMTYPEMASK 4095L
/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    toByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_toByte
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    toBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_toBoolean
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    toShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_toShort
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    toInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_toInt
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    toFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_toFloat
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    toDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_toDouble
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    toError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_toError
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    toDate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_toDate
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_toString
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    toDataArray
 * Signature: ()Lorg/adaptinet/sdk/fastcache/DataArray;
 */
JNIEXPORT jobject JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_toDataArray
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putEmpty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putEmpty
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putBoolean
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putByte
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putByte
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putShort
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putShort
  (JNIEnv *, jobject, jshort);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putError
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putError
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putDate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putDate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    putDataArray
 * Signature: (Lorg/adaptinet/sdk/fastcache/DataArray;)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_putDataArray
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getByte
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getChar
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getBoolean
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getInt
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getShort
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getLong
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getFloat
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getError
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getError
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getDateasLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getDateasLong
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getString
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getDataArray
 * Signature: (Lorg/adaptinet/sdk/fastcache/DataArray;)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getDataArray
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    noParam
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_noParam
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    getDataType
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_getDataType
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    DataItemClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_DataItemClear
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_release
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_init
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    clone
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_clone
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    changeType
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_changeType
  (JNIEnv *, jobject, jshort);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    Save
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_Save
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    Load
 * Signature: (Ljava/io/ByteArrayInputStream;)V
 */
JNIEXPORT void JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_Load
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    cloneIndirect
 * Signature: ()Lorg/adaptinet/sdk/fastcache/DataItem;
 */
JNIEXPORT jobject JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_cloneIndirect
  (JNIEnv *, jobject);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    unMarshal
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_unMarshal
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_adaptinet_sdk_fastcache_DataItem
 * Method:    marshal
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_adaptinet_sdk_fastcache_DataItem_marshal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
