// Title:        AddImpactedSwapDivCcyResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class AddImpactedSwapDivCcyResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getaddedIdsCount() { 
		return _addedIdsCount;
	}
	public Integer[] getaddedIdsArray() { 
		return _addedIds;
	}
	public void setaddedIdsArray(Integer newValue[]) { 
		_addedIds=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getaddedIdsIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_addedIds==null) return false;
				if(last<0) {
					last = _addedIds.length;
					while(--last>-1&&_addedIds[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _addedIds[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_addedIds[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public int getaddedIds(int idx) { 
		return _addedIds[idx].intValue();
	}
	public void setaddedIds(int newValue) { 
		if(_addedIds!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_addedIds.length;__I_A++) {
				if(_addedIds[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_addedIds.length;
				Integer array[] = new Integer[__OPEN_A+10];
				System.arraycopy(_addedIds,0,array,0,_addedIds.length);
				_addedIds = array;
			}
			_addedIds[__OPEN_A] = new Integer(newValue);
		}
		else {
			_addedIds = new Integer[10];
			_addedIds[0] = Integer.valueOf(newValue);
		}
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_addedIds!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _addedIdsCount);
			for(int __I_A=0;__I_A<_addedIdsCount;__I_A++) {
				daChild.setInt(__I_A, _addedIds[__I_A]);
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_addedIdsCount = daItem.getElements();
		if(_addedIdsCount>0) {
			_addedIds = new Integer [(int)_addedIdsCount];
			for(int __I_A=0;__I_A<_addedIdsCount;__I_A++) {
				_addedIds[__I_A] = new Integer(daItem.getInt(__I_A));
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private Integer _addedIds[] = null;
	private long _addedIdsCount = 0;
	private DataItem item = new DataItem();
}

