// Title:        CreateExceptionResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class CreateExceptionResponse implements FastCacheDVOBase  {
	public long getresponseParamCount() { 
		return _responseParamCount;
	}
	public ResponseParams[] getresponseParamArray() { 
		return _responseParam;
	}
	public void setresponseParamArray(ResponseParams newValue[]) { 
		_responseParam=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getresponseParamIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_responseParam==null) return false;
				if(last<0) {
					last = _responseParam.length;
					while(--last>-1&&_responseParam[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _responseParam[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_responseParam[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public ResponseParams getresponseParam(int idx) { 
		return (ResponseParams)_responseParam[idx];
	}
	public void setresponseParam(ResponseParams newValue) { 
		if(_responseParam!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_responseParam.length;__I_A++) {
				if(_responseParam[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_responseParam.length;
				ResponseParams array[] = new ResponseParams[__OPEN_A+10];
				System.arraycopy(_responseParam,0,array,0,_responseParam.length);
				_responseParam = array;
			}
			_responseParam[__OPEN_A] = newValue;
		}
		else {
			_responseParam = new ResponseParams[10];
			_responseParam[0] = newValue;
		}
		_responseParamCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 1);
		if(_responseParam!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _responseParamCount);
			for(int __I_A=0;__I_A<_responseParamCount;__I_A++) {
				daChild.setDataArray(__I_A, _responseParam[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_responseParamCount = daItem.getElements();
		if(_responseParamCount>0) {
			_responseParam = new ResponseParams [(int)_responseParamCount];
			for(int __I_A=0;__I_A<_responseParamCount;__I_A++) {
				_responseParam[__I_A] = new ResponseParams();
				daItem.getDataArray(__I_A, daElement);
				_responseParam[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ResponseParams _responseParam[] = null;
	private long _responseParamCount = 0;
	private DataItem item = new DataItem();
}

