// Title:        ExceptionReRateRequest
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class ExceptionReRateRequest implements FastCacheDVOBase  {
	public long getreRateExceptionParamsCount() { 
		return _reRateExceptionParamsCount;
	}
	public ReRateExceptionParams[] getreRateExceptionParamsArray() { 
		return _reRateExceptionParams;
	}
	public void setreRateExceptionParamsArray(ReRateExceptionParams newValue[]) { 
		_reRateExceptionParams=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getreRateExceptionParamsIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_reRateExceptionParams==null) return false;
				if(last<0) {
					last = _reRateExceptionParams.length;
					while(--last>-1&&_reRateExceptionParams[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _reRateExceptionParams[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_reRateExceptionParams[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public ReRateExceptionParams getreRateExceptionParams(int idx) { 
		return (ReRateExceptionParams)_reRateExceptionParams[idx];
	}
	public void setreRateExceptionParams(ReRateExceptionParams newValue) { 
		if(_reRateExceptionParams!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_reRateExceptionParams.length;__I_A++) {
				if(_reRateExceptionParams[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_reRateExceptionParams.length;
				ReRateExceptionParams array[] = new ReRateExceptionParams[__OPEN_A+10];
				System.arraycopy(_reRateExceptionParams,0,array,0,_reRateExceptionParams.length);
				_reRateExceptionParams = array;
			}
			_reRateExceptionParams[__OPEN_A] = newValue;
		}
		else {
			_reRateExceptionParams = new ReRateExceptionParams[10];
			_reRateExceptionParams[0] = newValue;
		}
		_reRateExceptionParamsCount++;
	}
	public int getuserId() {
		return _userId;
	}
	public void setuserId(int newValue) {
		_userId = newValue;
	}
	public boolean getisTrader() {
		return _isTrader;
	}
	public void setisTrader(boolean newValue) {
		_isTrader = newValue;
	}
	public int getlocation() {
		return _location;
	}
	public void setlocation(int newValue) {
		_location = newValue;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 4);
		if(_reRateExceptionParams!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _reRateExceptionParamsCount);
			for(int __I_A=0;__I_A<_reRateExceptionParamsCount;__I_A++) {
				daChild.setDataArray(__I_A, _reRateExceptionParams[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.putInt(_userId);
		da.setDataItem(sa_idx++, item);
		item.putBoolean(_isTrader);
		da.setDataItem(sa_idx++, item);
		item.putInt(_location);
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_reRateExceptionParamsCount = daItem.getElements();
		if(_reRateExceptionParamsCount>0) {
			_reRateExceptionParams = new ReRateExceptionParams [(int)_reRateExceptionParamsCount];
			for(int __I_A=0;__I_A<_reRateExceptionParamsCount;__I_A++) {
				_reRateExceptionParams[__I_A] = new ReRateExceptionParams();
				daItem.getDataArray(__I_A, daElement);
				_reRateExceptionParams[__I_A].readCache(daElement);
			}
		}
		in.getDataItem(sa_idx++, item);
		_userId = item.getInt();
		in.getDataItem(sa_idx++, item);
		_isTrader = item.getBoolean();
		in.getDataItem(sa_idx++, item);
		_location = item.getInt();
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReRateExceptionParams _reRateExceptionParams[] = null;
	private long _reRateExceptionParamsCount = 0;
	private int _userId;
	private boolean _isTrader;
	private int _location;
	private DataItem item = new DataItem();
}

