// Title:        FXRateList
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class FXRateList implements FastCacheDVOBase  {
	public long getfxRateCount() { 
		return _fxRateCount;
	}
	public FXRate[] getfxRateArray() { 
		return _fxRate;
	}
	public void setfxRateArray(FXRate newValue[]) { 
		_fxRate=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getfxRateIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_fxRate==null) return false;
				if(last<0) {
					last = _fxRate.length;
					while(--last>-1&&_fxRate[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _fxRate[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_fxRate[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public FXRate getfxRate(int idx) { 
		return (FXRate)_fxRate[idx];
	}
	public void setfxRate(FXRate newValue) { 
		if(_fxRate!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_fxRate.length;__I_A++) {
				if(_fxRate[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_fxRate.length;
				FXRate array[] = new FXRate[__OPEN_A+10];
				System.arraycopy(_fxRate,0,array,0,_fxRate.length);
				_fxRate = array;
			}
			_fxRate[__OPEN_A] = newValue;
		}
		else {
			_fxRate = new FXRate[10];
			_fxRate[0] = newValue;
		}
		_fxRateCount++;
	}
	public String getmajorCcy() {
		if(_majorCcy!=null) {
			return new String(_majorCcy);
		}
		else {
			return null;
		}
	}
	public void setmajorCcy(String newValue) {
		_majorCcy = newValue!=null ? newValue.toCharArray() : null;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		if(_fxRate!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _fxRateCount);
			for(int __I_A=0;__I_A<_fxRateCount;__I_A++) {
				daChild.setDataArray(__I_A, _fxRate[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_majorCcy);
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_fxRateCount = daItem.getElements();
		if(_fxRateCount>0) {
			_fxRate = new FXRate [(int)_fxRateCount];
			for(int __I_A=0;__I_A<_fxRateCount;__I_A++) {
				_fxRate[__I_A] = new FXRate();
				daItem.getDataArray(__I_A, daElement);
				_fxRate[__I_A].readCache(daElement);
			}
		}
		in.getDataItem(sa_idx++, item);
		_majorCcy = item.getCharArray();
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private FXRate _fxRate[] = null;
	private long _fxRateCount = 0;
	private char[] _majorCcy;
	private DataItem item = new DataItem();
}

