// Title:        GetCurrenciesResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetCurrenciesResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getcurrenyCount() { 
		return _currenyCount;
	}
	public Currency[] getcurrenyArray() { 
		return _curreny;
	}
	public void setcurrenyArray(Currency newValue[]) { 
		_curreny=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getcurrenyIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_curreny==null) return false;
				if(last<0) {
					last = _curreny.length;
					while(--last>-1&&_curreny[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _curreny[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_curreny[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public Currency getcurreny(int idx) { 
		return (Currency)_curreny[idx];
	}
	public void setcurreny(Currency newValue) { 
		if(_curreny!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_curreny.length;__I_A++) {
				if(_curreny[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_curreny.length;
				Currency array[] = new Currency[__OPEN_A+10];
				System.arraycopy(_curreny,0,array,0,_curreny.length);
				_curreny = array;
			}
			_curreny[__OPEN_A] = newValue;
		}
		else {
			_curreny = new Currency[10];
			_curreny[0] = newValue;
		}
		_currenyCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_curreny!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _currenyCount);
			for(int __I_A=0;__I_A<_currenyCount;__I_A++) {
				daChild.setDataArray(__I_A, _curreny[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_currenyCount = daItem.getElements();
		if(_currenyCount>0) {
			_curreny = new Currency [(int)_currenyCount];
			for(int __I_A=0;__I_A<_currenyCount;__I_A++) {
				_curreny[__I_A] = new Currency();
				daItem.getDataArray(__I_A, daElement);
				_curreny[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private Currency _curreny[] = null;
	private long _currenyCount = 0;
	private DataItem item = new DataItem();
}

