// Title:        GetDesksResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetDesksResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getdeskCount() { 
		return _deskCount;
	}
	public Desk[] getdeskArray() { 
		return _desk;
	}
	public void setdeskArray(Desk newValue[]) { 
		_desk=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getdeskIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_desk==null) return false;
				if(last<0) {
					last = _desk.length;
					while(--last>-1&&_desk[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _desk[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_desk[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public Desk getdesk(int idx) { 
		return (Desk)_desk[idx];
	}
	public void setdesk(Desk newValue) { 
		if(_desk!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_desk.length;__I_A++) {
				if(_desk[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_desk.length;
				Desk array[] = new Desk[__OPEN_A+10];
				System.arraycopy(_desk,0,array,0,_desk.length);
				_desk = array;
			}
			_desk[__OPEN_A] = newValue;
		}
		else {
			_desk = new Desk[10];
			_desk[0] = newValue;
		}
		_deskCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_desk!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _deskCount);
			for(int __I_A=0;__I_A<_deskCount;__I_A++) {
				daChild.setDataArray(__I_A, _desk[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_deskCount = daItem.getElements();
		if(_deskCount>0) {
			_desk = new Desk [(int)_deskCount];
			for(int __I_A=0;__I_A<_deskCount;__I_A++) {
				_desk[__I_A] = new Desk();
				daItem.getDataArray(__I_A, daElement);
				_desk[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private Desk _desk[] = null;
	private long _deskCount = 0;
	private DataItem item = new DataItem();
}

