// Title:        GetDividendSpillResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetDividendSpillResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getdividendSpillCount() { 
		return _dividendSpillCount;
	}
	public DividendSpill[] getdividendSpillArray() { 
		return _dividendSpill;
	}
	public void setdividendSpillArray(DividendSpill newValue[]) { 
		_dividendSpill=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getdividendSpillIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_dividendSpill==null) return false;
				if(last<0) {
					last = _dividendSpill.length;
					while(--last>-1&&_dividendSpill[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _dividendSpill[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_dividendSpill[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public DividendSpill getdividendSpill(int idx) { 
		return (DividendSpill)_dividendSpill[idx];
	}
	public void setdividendSpill(DividendSpill newValue) { 
		if(_dividendSpill!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_dividendSpill.length;__I_A++) {
				if(_dividendSpill[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_dividendSpill.length;
				DividendSpill array[] = new DividendSpill[__OPEN_A+10];
				System.arraycopy(_dividendSpill,0,array,0,_dividendSpill.length);
				_dividendSpill = array;
			}
			_dividendSpill[__OPEN_A] = newValue;
		}
		else {
			_dividendSpill = new DividendSpill[10];
			_dividendSpill[0] = newValue;
		}
		_dividendSpillCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_dividendSpill!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _dividendSpillCount);
			for(int __I_A=0;__I_A<_dividendSpillCount;__I_A++) {
				daChild.setDataArray(__I_A, _dividendSpill[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_dividendSpillCount = daItem.getElements();
		if(_dividendSpillCount>0) {
			_dividendSpill = new DividendSpill [(int)_dividendSpillCount];
			for(int __I_A=0;__I_A<_dividendSpillCount;__I_A++) {
				_dividendSpill[__I_A] = new DividendSpill();
				daItem.getDataArray(__I_A, daElement);
				_dividendSpill[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private DividendSpill _dividendSpill[] = null;
	private long _dividendSpillCount = 0;
	private DataItem item = new DataItem();
}

