// Title:        GetInstitutionResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetInstitutionResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getinstitutionsCount() { 
		return _institutionsCount;
	}
	public Institution[] getinstitutionsArray() { 
		return _institutions;
	}
	public void setinstitutionsArray(Institution newValue[]) { 
		_institutions=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getinstitutionsIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_institutions==null) return false;
				if(last<0) {
					last = _institutions.length;
					while(--last>-1&&_institutions[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _institutions[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_institutions[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public Institution getinstitutions(int idx) { 
		return (Institution)_institutions[idx];
	}
	public void setinstitutions(Institution newValue) { 
		if(_institutions!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_institutions.length;__I_A++) {
				if(_institutions[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_institutions.length;
				Institution array[] = new Institution[__OPEN_A+10];
				System.arraycopy(_institutions,0,array,0,_institutions.length);
				_institutions = array;
			}
			_institutions[__OPEN_A] = newValue;
		}
		else {
			_institutions = new Institution[10];
			_institutions[0] = newValue;
		}
		_institutionsCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_institutions!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _institutionsCount);
			for(int __I_A=0;__I_A<_institutionsCount;__I_A++) {
				daChild.setDataArray(__I_A, _institutions[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_institutionsCount = daItem.getElements();
		if(_institutionsCount>0) {
			_institutions = new Institution [(int)_institutionsCount];
			for(int __I_A=0;__I_A<_institutionsCount;__I_A++) {
				_institutions[__I_A] = new Institution();
				daItem.getDataArray(__I_A, daElement);
				_institutions[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private Institution _institutions[] = null;
	private long _institutionsCount = 0;
	private DataItem item = new DataItem();
}

