// Title:        GetInstrumentResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetInstrumentResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getinstrumentsCount() { 
		return _instrumentsCount;
	}
	public Instrument[] getinstrumentsArray() { 
		return _instruments;
	}
	public void setinstrumentsArray(Instrument newValue[]) { 
		_instruments=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getinstrumentsIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_instruments==null) return false;
				if(last<0) {
					last = _instruments.length;
					while(--last>-1&&_instruments[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _instruments[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_instruments[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public Instrument getinstruments(int idx) { 
		return (Instrument)_instruments[idx];
	}
	public void setinstruments(Instrument newValue) { 
		if(_instruments!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_instruments.length;__I_A++) {
				if(_instruments[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_instruments.length;
				Instrument array[] = new Instrument[__OPEN_A+10];
				System.arraycopy(_instruments,0,array,0,_instruments.length);
				_instruments = array;
			}
			_instruments[__OPEN_A] = newValue;
		}
		else {
			_instruments = new Instrument[10];
			_instruments[0] = newValue;
		}
		_instrumentsCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_instruments!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _instrumentsCount);
			for(int __I_A=0;__I_A<_instrumentsCount;__I_A++) {
				daChild.setDataArray(__I_A, _instruments[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_instrumentsCount = daItem.getElements();
		if(_instrumentsCount>0) {
			_instruments = new Instrument [(int)_instrumentsCount];
			for(int __I_A=0;__I_A<_instrumentsCount;__I_A++) {
				_instruments[__I_A] = new Instrument();
				daItem.getDataArray(__I_A, daElement);
				_instruments[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private Instrument _instruments[] = null;
	private long _instrumentsCount = 0;
	private DataItem item = new DataItem();
}

