// Title:        GetInstrumentAuditResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetInstrumentAuditResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getInstrumentAuditCount() { 
		return _InstrumentAuditCount;
	}
	public InstrumentAudit[] getInstrumentAuditArray() { 
		return _InstrumentAudit;
	}
	public void setInstrumentAuditArray(InstrumentAudit newValue[]) { 
		_InstrumentAudit=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getInstrumentAuditIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_InstrumentAudit==null) return false;
				if(last<0) {
					last = _InstrumentAudit.length;
					while(--last>-1&&_InstrumentAudit[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _InstrumentAudit[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_InstrumentAudit[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public InstrumentAudit getInstrumentAudit(int idx) { 
		return (InstrumentAudit)_InstrumentAudit[idx];
	}
	public void setInstrumentAudit(InstrumentAudit newValue) { 
		if(_InstrumentAudit!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_InstrumentAudit.length;__I_A++) {
				if(_InstrumentAudit[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_InstrumentAudit.length;
				InstrumentAudit array[] = new InstrumentAudit[__OPEN_A+10];
				System.arraycopy(_InstrumentAudit,0,array,0,_InstrumentAudit.length);
				_InstrumentAudit = array;
			}
			_InstrumentAudit[__OPEN_A] = newValue;
		}
		else {
			_InstrumentAudit = new InstrumentAudit[10];
			_InstrumentAudit[0] = newValue;
		}
		_InstrumentAuditCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_InstrumentAudit!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _InstrumentAuditCount);
			for(int __I_A=0;__I_A<_InstrumentAuditCount;__I_A++) {
				daChild.setDataArray(__I_A, _InstrumentAudit[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_InstrumentAuditCount = daItem.getElements();
		if(_InstrumentAuditCount>0) {
			_InstrumentAudit = new InstrumentAudit [(int)_InstrumentAuditCount];
			for(int __I_A=0;__I_A<_InstrumentAuditCount;__I_A++) {
				_InstrumentAudit[__I_A] = new InstrumentAudit();
				daItem.getDataArray(__I_A, daElement);
				_InstrumentAudit[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private InstrumentAudit _InstrumentAudit[] = null;
	private long _InstrumentAuditCount = 0;
	private DataItem item = new DataItem();
}

