// Title:        GetLegalEntityResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetLegalEntityResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getlegalEntitiesCount() { 
		return _legalEntitiesCount;
	}
	public LegalEntity[] getlegalEntitiesArray() { 
		return _legalEntities;
	}
	public void setlegalEntitiesArray(LegalEntity newValue[]) { 
		_legalEntities=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getlegalEntitiesIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_legalEntities==null) return false;
				if(last<0) {
					last = _legalEntities.length;
					while(--last>-1&&_legalEntities[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _legalEntities[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_legalEntities[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public LegalEntity getlegalEntities(int idx) { 
		return (LegalEntity)_legalEntities[idx];
	}
	public void setlegalEntities(LegalEntity newValue) { 
		if(_legalEntities!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_legalEntities.length;__I_A++) {
				if(_legalEntities[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_legalEntities.length;
				LegalEntity array[] = new LegalEntity[__OPEN_A+10];
				System.arraycopy(_legalEntities,0,array,0,_legalEntities.length);
				_legalEntities = array;
			}
			_legalEntities[__OPEN_A] = newValue;
		}
		else {
			_legalEntities = new LegalEntity[10];
			_legalEntities[0] = newValue;
		}
		_legalEntitiesCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_legalEntities!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _legalEntitiesCount);
			for(int __I_A=0;__I_A<_legalEntitiesCount;__I_A++) {
				daChild.setDataArray(__I_A, _legalEntities[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_legalEntitiesCount = daItem.getElements();
		if(_legalEntitiesCount>0) {
			_legalEntities = new LegalEntity [(int)_legalEntitiesCount];
			for(int __I_A=0;__I_A<_legalEntitiesCount;__I_A++) {
				_legalEntities[__I_A] = new LegalEntity();
				daItem.getDataArray(__I_A, daElement);
				_legalEntities[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private LegalEntity _legalEntities[] = null;
	private long _legalEntitiesCount = 0;
	private DataItem item = new DataItem();
}

