// Title:        GetLegalEntityAuditResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetLegalEntityAuditResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getlegalEntityAuditCount() { 
		return _legalEntityAuditCount;
	}
	public LegalEntityAudit[] getlegalEntityAuditArray() { 
		return _legalEntityAudit;
	}
	public void setlegalEntityAuditArray(LegalEntityAudit newValue[]) { 
		_legalEntityAudit=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getlegalEntityAuditIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_legalEntityAudit==null) return false;
				if(last<0) {
					last = _legalEntityAudit.length;
					while(--last>-1&&_legalEntityAudit[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _legalEntityAudit[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_legalEntityAudit[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public LegalEntityAudit getlegalEntityAudit(int idx) { 
		return (LegalEntityAudit)_legalEntityAudit[idx];
	}
	public void setlegalEntityAudit(LegalEntityAudit newValue) { 
		if(_legalEntityAudit!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_legalEntityAudit.length;__I_A++) {
				if(_legalEntityAudit[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_legalEntityAudit.length;
				LegalEntityAudit array[] = new LegalEntityAudit[__OPEN_A+10];
				System.arraycopy(_legalEntityAudit,0,array,0,_legalEntityAudit.length);
				_legalEntityAudit = array;
			}
			_legalEntityAudit[__OPEN_A] = newValue;
		}
		else {
			_legalEntityAudit = new LegalEntityAudit[10];
			_legalEntityAudit[0] = newValue;
		}
		_legalEntityAuditCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_legalEntityAudit!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _legalEntityAuditCount);
			for(int __I_A=0;__I_A<_legalEntityAuditCount;__I_A++) {
				daChild.setDataArray(__I_A, _legalEntityAudit[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_legalEntityAuditCount = daItem.getElements();
		if(_legalEntityAuditCount>0) {
			_legalEntityAudit = new LegalEntityAudit [(int)_legalEntityAuditCount];
			for(int __I_A=0;__I_A<_legalEntityAuditCount;__I_A++) {
				_legalEntityAudit[__I_A] = new LegalEntityAudit();
				daItem.getDataArray(__I_A, daElement);
				_legalEntityAudit[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private LegalEntityAudit _legalEntityAudit[] = null;
	private long _legalEntityAuditCount = 0;
	private DataItem item = new DataItem();
}

