// Title:        GetPendingExceptionCountResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetPendingExceptionCountResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getpendingExceptionAlertCount() { 
		return _pendingExceptionAlertCount;
	}
	public PendingExceptionAlert[] getpendingExceptionAlertArray() { 
		return _pendingExceptionAlert;
	}
	public void setpendingExceptionAlertArray(PendingExceptionAlert newValue[]) { 
		_pendingExceptionAlert=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getpendingExceptionAlertIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_pendingExceptionAlert==null) return false;
				if(last<0) {
					last = _pendingExceptionAlert.length;
					while(--last>-1&&_pendingExceptionAlert[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _pendingExceptionAlert[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_pendingExceptionAlert[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public PendingExceptionAlert getpendingExceptionAlert(int idx) { 
		return (PendingExceptionAlert)_pendingExceptionAlert[idx];
	}
	public void setpendingExceptionAlert(PendingExceptionAlert newValue) { 
		if(_pendingExceptionAlert!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_pendingExceptionAlert.length;__I_A++) {
				if(_pendingExceptionAlert[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_pendingExceptionAlert.length;
				PendingExceptionAlert array[] = new PendingExceptionAlert[__OPEN_A+10];
				System.arraycopy(_pendingExceptionAlert,0,array,0,_pendingExceptionAlert.length);
				_pendingExceptionAlert = array;
			}
			_pendingExceptionAlert[__OPEN_A] = newValue;
		}
		else {
			_pendingExceptionAlert = new PendingExceptionAlert[10];
			_pendingExceptionAlert[0] = newValue;
		}
		_pendingExceptionAlertCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_pendingExceptionAlert!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _pendingExceptionAlertCount);
			for(int __I_A=0;__I_A<_pendingExceptionAlertCount;__I_A++) {
				daChild.setDataArray(__I_A, _pendingExceptionAlert[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_pendingExceptionAlertCount = daItem.getElements();
		if(_pendingExceptionAlertCount>0) {
			_pendingExceptionAlert = new PendingExceptionAlert [(int)_pendingExceptionAlertCount];
			for(int __I_A=0;__I_A<_pendingExceptionAlertCount;__I_A++) {
				_pendingExceptionAlert[__I_A] = new PendingExceptionAlert();
				daItem.getDataArray(__I_A, daElement);
				_pendingExceptionAlert[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private PendingExceptionAlert _pendingExceptionAlert[] = new PendingExceptionAlert[10];
	private long _pendingExceptionAlertCount = 0;
	private DataItem item = new DataItem();
}

