// Title:        GetSecurityIdMappingRequest
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetSecurityIdMappingRequest implements FastCacheDVOBase  {
	public long getsecurityIdCount() { 
		return _securityIdCount;
	}
	public String[] getsecurityIdArray() { 
		return _securityId;
	}
	public void setsecurityIdArray(String newValue[]) { 
		_securityId=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getsecurityIdIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_securityId==null) return false;
				if(last<0) {
					last = _securityId.length;
					while(--last>-1&&_securityId[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _securityId[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_securityId[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public String getsecurityId(int idx) { 
		return (String)_securityId[idx];
	}
	public void setsecurityId(String newValue) { 
		if(_securityId!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_securityId.length;__I_A++) {
				if(_securityId[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_securityId.length;
				String array[] = new String[__OPEN_A+10];
				System.arraycopy(_securityId,0,array,0,_securityId.length);
				_securityId = array;
			}
			_securityId[__OPEN_A] = newValue;
		}
		else {
			_securityId = new String[10];
			_securityId[0] = newValue;
		}
		_securityIdCount++;
	}
	public int getlocation() {
		return _location;
	}
	public void setlocation(int newValue) {
		_location = newValue;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		if(_securityId!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _securityIdCount);
			for(int __I_A=0;__I_A<_securityIdCount;__I_A++) {
				daChild.setString(__I_A, _securityId[__I_A]);
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.putInt(_location);
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_securityIdCount = daItem.getElements();
		if(_securityIdCount>0) {
			_securityId = new String [(int)_securityIdCount];
			for(int __I_A=0;__I_A<_securityIdCount;__I_A++) {
				_securityId[__I_A] = new String(daItem.getString(__I_A));
			}
		}
		in.getDataItem(sa_idx++, item);
		_location = item.getInt();
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private String _securityId[] = null;
	private long _securityIdCount = 0;
	private int _location;
	private DataItem item = new DataItem();
}

