// Title:        GetSwapTransactionResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetSwapTransactionResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getswapTransactionsCount() { 
		return _swapTransactionsCount;
	}
	public SwapTransaction[] getswapTransactionsArray() { 
		return _swapTransactions;
	}
	public void setswapTransactionsArray(SwapTransaction newValue[]) { 
		_swapTransactions=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getswapTransactionsIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_swapTransactions==null) return false;
				if(last<0) {
					last = _swapTransactions.length;
					while(--last>-1&&_swapTransactions[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _swapTransactions[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_swapTransactions[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public SwapTransaction getswapTransactions(int idx) { 
		return (SwapTransaction)_swapTransactions[idx];
	}
	public void setswapTransactions(SwapTransaction newValue) { 
		if(_swapTransactions!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_swapTransactions.length;__I_A++) {
				if(_swapTransactions[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_swapTransactions.length;
				SwapTransaction array[] = new SwapTransaction[__OPEN_A+10];
				System.arraycopy(_swapTransactions,0,array,0,_swapTransactions.length);
				_swapTransactions = array;
			}
			_swapTransactions[__OPEN_A] = newValue;
		}
		else {
			_swapTransactions = new SwapTransaction[10];
			_swapTransactions[0] = newValue;
		}
		_swapTransactionsCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_swapTransactions!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _swapTransactionsCount);
			for(int __I_A=0;__I_A<_swapTransactionsCount;__I_A++) {
				daChild.setDataArray(__I_A, _swapTransactions[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_swapTransactionsCount = daItem.getElements();
		if(_swapTransactionsCount>0) {
			_swapTransactions = new SwapTransaction [(int)_swapTransactionsCount];
			for(int __I_A=0;__I_A<_swapTransactionsCount;__I_A++) {
				_swapTransactions[__I_A] = new SwapTransaction();
				daItem.getDataArray(__I_A, daElement);
				_swapTransactions[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private SwapTransaction _swapTransactions[] = null;
	private long _swapTransactionsCount = 0;
	private DataItem item = new DataItem();
}

