// Title:        GetTradeResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetTradeResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long gettradesCount() { 
		return _tradesCount;
	}
	public Trade[] gettradesArray() { 
		return _trades;
	}
	public void settradesArray(Trade newValue[]) { 
		_trades=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator gettradesIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_trades==null) return false;
				if(last<0) {
					last = _trades.length;
					while(--last>-1&&_trades[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _trades[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_trades[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public Trade gettrades(int idx) { 
		return (Trade)_trades[idx];
	}
	public void settrades(Trade newValue) { 
		if(_trades!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_trades.length;__I_A++) {
				if(_trades[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_trades.length;
				Trade array[] = new Trade[__OPEN_A+10];
				System.arraycopy(_trades,0,array,0,_trades.length);
				_trades = array;
			}
			_trades[__OPEN_A] = newValue;
		}
		else {
			_trades = new Trade[10];
			_trades[0] = newValue;
		}
		_tradesCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_trades!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _tradesCount);
			for(int __I_A=0;__I_A<_tradesCount;__I_A++) {
				daChild.setDataArray(__I_A, _trades[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_tradesCount = daItem.getElements();
		if(_tradesCount>0) {
			_trades = new Trade [(int)_tradesCount];
			for(int __I_A=0;__I_A<_tradesCount;__I_A++) {
				_trades[__I_A] = new Trade();
				daItem.getDataArray(__I_A, daElement);
				_trades[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private Trade _trades[] = null;
	private long _tradesCount = 0;
	private DataItem item = new DataItem();
}

