// Title:        GetTradeDividendsResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class GetTradeDividendsResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getdividendsCount() { 
		return _dividendsCount;
	}
	public TradeDividend[] getdividendsArray() { 
		return _dividends;
	}
	public void setdividendsArray(TradeDividend newValue[]) { 
		_dividends=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getdividendsIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_dividends==null) return false;
				if(last<0) {
					last = _dividends.length;
					while(--last>-1&&_dividends[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _dividends[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_dividends[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public TradeDividend getdividends(int idx) { 
		return (TradeDividend)_dividends[idx];
	}
	public void setdividends(TradeDividend newValue) { 
		if(_dividends!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_dividends.length;__I_A++) {
				if(_dividends[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_dividends.length;
				TradeDividend array[] = new TradeDividend[__OPEN_A+10];
				System.arraycopy(_dividends,0,array,0,_dividends.length);
				_dividends = array;
			}
			_dividends[__OPEN_A] = newValue;
		}
		else {
			_dividends = new TradeDividend[10];
			_dividends[0] = newValue;
		}
		_dividendsCount++;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_dividends!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _dividendsCount);
			for(int __I_A=0;__I_A<_dividendsCount;__I_A++) {
				daChild.setDataArray(__I_A, _dividends[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_dividendsCount = daItem.getElements();
		if(_dividendsCount>0) {
			_dividends = new TradeDividend [(int)_dividendsCount];
			for(int __I_A=0;__I_A<_dividendsCount;__I_A++) {
				_dividends[__I_A] = new TradeDividend();
				daItem.getDataArray(__I_A, daElement);
				_dividends[__I_A].readCache(daElement);
			}
		}
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private TradeDividend _dividends[] = null;
	private long _dividendsCount = 0;
	private DataItem item = new DataItem();
}

