// Title:        Institution
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class Institution implements FastCacheDVOBase  {
	public int getinstitutionId() {
		return _institutionId;
	}
	public void setinstitutionId(int newValue) {
		_institutionId = newValue;
	}
	public String getinstitutionName() {
		if(_institutionName!=null) {
			return new String(_institutionName);
		}
		else {
			return null;
		}
	}
	public void setinstitutionName(String newValue) {
		_institutionName = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getlegalEntityName() {
		if(_legalEntityName!=null) {
			return new String(_legalEntityName);
		}
		else {
			return null;
		}
	}
	public void setlegalEntityName(String newValue) {
		_legalEntityName = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getinstitutionFullName() {
		if(_institutionFullName!=null) {
			return new String(_institutionFullName);
		}
		else {
			return null;
		}
	}
	public void setinstitutionFullName(String newValue) {
		_institutionFullName = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getmnemonic() {
		if(_mnemonic!=null) {
			return new String(_mnemonic);
		}
		else {
			return null;
		}
	}
	public void setmnemonic(String newValue) {
		_mnemonic = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getpbgoInvestmentManagerId() {
		if(_pbgoInvestmentManagerId!=null) {
			return new String(_pbgoInvestmentManagerId);
		}
		else {
			return null;
		}
	}
	public void setpbgoInvestmentManagerId(String newValue) {
		_pbgoInvestmentManagerId = newValue!=null ? newValue.toCharArray() : null;
	}
	public int getparagonId() {
		return _paragonId;
	}
	public void setparagonId(int newValue) {
		_paragonId = newValue;
	}
	public String getcportParentId() {
		if(_cportParentId!=null) {
			return new String(_cportParentId);
		}
		else {
			return null;
		}
	}
	public void setcportParentId(String newValue) {
		_cportParentId = newValue!=null ? newValue.toCharArray() : null;
	}
	public boolean getdbagEntityFlag() {
		return _dbagEntityFlag;
	}
	public void setdbagEntityFlag(boolean newValue) {
		_dbagEntityFlag = newValue;
	}
	public boolean getbrokerDealerFlag() {
		return _brokerDealerFlag;
	}
	public void setbrokerDealerFlag(boolean newValue) {
		_brokerDealerFlag = newValue;
	}
	public boolean getprimaryDealerFlag() {
		return _primaryDealerFlag;
	}
	public void setprimaryDealerFlag(boolean newValue) {
		_primaryDealerFlag = newValue;
	}
	public boolean getpbgoInstitutionFlag() {
		return _pbgoInstitutionFlag;
	}
	public void setpbgoInstitutionFlag(boolean newValue) {
		_pbgoInstitutionFlag = newValue;
	}
	public int gettotalReturnSwapClientFlag() {
		return _totalReturnSwapClientFlag;
	}
	public void settotalReturnSwapClientFlag(int newValue) {
		_totalReturnSwapClientFlag = newValue;
	}
	public String getcomment() {
		if(_comment!=null) {
			return new String(_comment);
		}
		else {
			return null;
		}
	}
	public void setcomment(String newValue) {
		_comment = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getcontactPerson() {
		if(_contactPerson!=null) {
			return new String(_contactPerson);
		}
		else {
			return null;
		}
	}
	public void setcontactPerson(String newValue) {
		_contactPerson = newValue!=null ? newValue.toCharArray() : null;
	}
	public String gettelephone() {
		if(_telephone!=null) {
			return new String(_telephone);
		}
		else {
			return null;
		}
	}
	public void settelephone(String newValue) {
		_telephone = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getfax() {
		if(_fax!=null) {
			return new String(_fax);
		}
		else {
			return null;
		}
	}
	public void setfax(String newValue) {
		_fax = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getaddress() {
		if(_address!=null) {
			return new String(_address);
		}
		else {
			return null;
		}
	}
	public void setaddress(String newValue) {
		_address = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getaddress2() {
		if(_address2!=null) {
			return new String(_address2);
		}
		else {
			return null;
		}
	}
	public void setaddress2(String newValue) {
		_address2 = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getcity() {
		if(_city!=null) {
			return new String(_city);
		}
		else {
			return null;
		}
	}
	public void setcity(String newValue) {
		_city = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getstate() {
		if(_state!=null) {
			return new String(_state);
		}
		else {
			return null;
		}
	}
	public void setstate(String newValue) {
		_state = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getcountry() {
		if(_country!=null) {
			return new String(_country);
		}
		else {
			return null;
		}
	}
	public void setcountry(String newValue) {
		_country = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getpostalCode() {
		if(_postalCode!=null) {
			return new String(_postalCode);
		}
		else {
			return null;
		}
	}
	public void setpostalCode(String newValue) {
		_postalCode = newValue!=null ? newValue.toCharArray() : null;
	}
	public String gettelex() {
		if(_telex!=null) {
			return new String(_telex);
		}
		else {
			return null;
		}
	}
	public void settelex(String newValue) {
		_telex = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getcisNumber() {
		if(_cisNumber!=null) {
			return new String(_cisNumber);
		}
		else {
			return null;
		}
	}
	public void setcisNumber(String newValue) {
		_cisNumber = newValue!=null ? newValue.toCharArray() : null;
	}
	public int getpriceDigits() {
		return _priceDigits;
	}
	public void setpriceDigits(int newValue) {
		_priceDigits = newValue;
	}
	public String getemailAddress() {
		if(_emailAddress!=null) {
			return new String(_emailAddress);
		}
		else {
			return null;
		}
	}
	public void setemailAddress(String newValue) {
		_emailAddress = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getessLocation() {
		if(_essLocation!=null) {
			return new String(_essLocation);
		}
		else {
			return null;
		}
	}
	public void setessLocation(String newValue) {
		_essLocation = newValue!=null ? newValue.toCharArray() : null;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 28);
		item.putInt(_institutionId);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_institutionName);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_legalEntityName);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_institutionFullName);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_mnemonic);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_pbgoInvestmentManagerId);
		da.setDataItem(sa_idx++, item);
		item.putInt(_paragonId);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_cportParentId);
		da.setDataItem(sa_idx++, item);
		item.putBoolean(_dbagEntityFlag);
		da.setDataItem(sa_idx++, item);
		item.putBoolean(_brokerDealerFlag);
		da.setDataItem(sa_idx++, item);
		item.putBoolean(_primaryDealerFlag);
		da.setDataItem(sa_idx++, item);
		item.putBoolean(_pbgoInstitutionFlag);
		da.setDataItem(sa_idx++, item);
		item.putInt(_totalReturnSwapClientFlag);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_comment);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_contactPerson);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_telephone);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_fax);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_address);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_address2);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_city);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_state);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_country);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_postalCode);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_telex);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_cisNumber);
		da.setDataItem(sa_idx++, item);
		item.putInt(_priceDigits);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_emailAddress);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_essLocation);
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		in.getDataItem(sa_idx++, item);
		_institutionId = item.getInt();
		in.getDataItem(sa_idx++, item);
		_institutionName = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_legalEntityName = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_institutionFullName = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_mnemonic = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_pbgoInvestmentManagerId = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_paragonId = item.getInt();
		in.getDataItem(sa_idx++, item);
		_cportParentId = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_dbagEntityFlag = item.getBoolean();
		in.getDataItem(sa_idx++, item);
		_brokerDealerFlag = item.getBoolean();
		in.getDataItem(sa_idx++, item);
		_primaryDealerFlag = item.getBoolean();
		in.getDataItem(sa_idx++, item);
		_pbgoInstitutionFlag = item.getBoolean();
		in.getDataItem(sa_idx++, item);
		_totalReturnSwapClientFlag = item.getInt();
		in.getDataItem(sa_idx++, item);
		_comment = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_contactPerson = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_telephone = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_fax = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_address = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_address2 = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_city = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_state = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_country = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_postalCode = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_telex = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_cisNumber = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_priceDigits = item.getInt();
		in.getDataItem(sa_idx++, item);
		_emailAddress = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_essLocation = item.getCharArray();
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private int _institutionId;
	private char[] _institutionName;
	private char[] _legalEntityName;
	private char[] _institutionFullName;
	private char[] _mnemonic;
	private char[] _pbgoInvestmentManagerId;
	private int _paragonId;
	private char[] _cportParentId;
	private boolean _dbagEntityFlag;
	private boolean _brokerDealerFlag;
	private boolean _primaryDealerFlag;
	private boolean _pbgoInstitutionFlag;
	private int _totalReturnSwapClientFlag;
	private char[] _comment;
	private char[] _contactPerson;
	private char[] _telephone;
	private char[] _fax;
	private char[] _address;
	private char[] _address2;
	private char[] _city;
	private char[] _state;
	private char[] _country;
	private char[] _postalCode;
	private char[] _telex;
	private char[] _cisNumber;
	private int _priceDigits;
	private char[] _emailAddress;
	private char[] _essLocation;
	private DataItem item = new DataItem();
}

