// Title:        InstitutionSwapBook
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class InstitutionSwapBook implements FastCacheDVOBase  {
	public int getbookId() {
		return _bookId;
	}
	public void setbookId(int newValue) {
		_bookId = newValue;
	}
	public String getaccountName() {
		if(_accountName!=null) {
			return new String(_accountName);
		}
		else {
			return null;
		}
	}
	public void setaccountName(String newValue) {
		_accountName = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getbookName() {
		if(_bookName!=null) {
			return new String(_bookName);
		}
		else {
			return null;
		}
	}
	public void setbookName(String newValue) {
		_bookName = newValue!=null ? newValue.toCharArray() : null;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 3);
		item.putInt(_bookId);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_accountName);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_bookName);
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		in.getDataItem(sa_idx++, item);
		_bookId = item.getInt();
		in.getDataItem(sa_idx++, item);
		_accountName = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_bookName = item.getCharArray();
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private int _bookId;
	private char[] _accountName;
	private char[] _bookName;
	private DataItem item = new DataItem();
}

