// Title:        PingResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class PingResponse implements FastCacheDVOBase  {
	public long getpushedDataCount() { 
		return _pushedDataCount;
	}
	public PushedData[] getpushedDataArray() { 
		return _pushedData;
	}
	public void setpushedDataArray(PushedData newValue[]) { 
		_pushedData=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getpushedDataIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_pushedData==null) return false;
				if(last<0) {
					last = _pushedData.length;
					while(--last>-1&&_pushedData[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _pushedData[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_pushedData[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public PushedData getpushedData(int idx) { 
		return (PushedData)_pushedData[idx];
	}
	public void setpushedData(PushedData newValue) { 
		if(_pushedData!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_pushedData.length;__I_A++) {
				if(_pushedData[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_pushedData.length;
				PushedData array[] = new PushedData[__OPEN_A+10];
				System.arraycopy(_pushedData,0,array,0,_pushedData.length);
				_pushedData = array;
			}
			_pushedData[__OPEN_A] = newValue;
		}
		else {
			_pushedData = new PushedData[10];
			_pushedData[0] = newValue;
		}
		_pushedDataCount++;
	}
	public int getcode() {
		return _code;
	}
	public void setcode(int newValue) {
		_code = newValue;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		if(_pushedData!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _pushedDataCount);
			for(int __I_A=0;__I_A<_pushedDataCount;__I_A++) {
				daChild.setDataArray(__I_A, _pushedData[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.putInt(_code);
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_pushedDataCount = daItem.getElements();
		if(_pushedDataCount>0) {
			_pushedData = new PushedData [(int)_pushedDataCount];
			for(int __I_A=0;__I_A<_pushedDataCount;__I_A++) {
				_pushedData[__I_A] = new PushedData();
				daItem.getDataArray(__I_A, daElement);
				_pushedData[__I_A].readCache(daElement);
			}
		}
		in.getDataItem(sa_idx++, item);
		_code = item.getInt();
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private PushedData _pushedData[] = null;
	private long _pushedDataCount = 0;
	private int _code;
	private DataItem item = new DataItem();
}

