// Title:        PingRequest
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class PingRequest implements FastCacheDVOBase  {
	public String getuserEmail() {
		if(_userEmail!=null) {
			return new String(_userEmail);
		}
		else {
			return null;
		}
	}
	public void setuserEmail(String newValue) {
		_userEmail = newValue!=null ? newValue.toCharArray() : null;
	}
	public String getipAddress() {
		if(_ipAddress!=null) {
			return new String(_ipAddress);
		}
		else {
			return null;
		}
	}
	public void setipAddress(String newValue) {
		_ipAddress = newValue!=null ? newValue.toCharArray() : null;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		item.putCharArray(_userEmail);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_ipAddress);
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		in.getDataItem(sa_idx++, item);
		_userEmail = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_ipAddress = item.getCharArray();
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private char[] _userEmail;
	private char[] _ipAddress;
	private DataItem item = new DataItem();
}

