// Title:        UpdateImpactedSwapDivCcyRequest
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class UpdateImpactedSwapDivCcyRequest implements FastCacheDVOBase  {
	public long getimpactedSwapDivCcysCount() { 
		return _impactedSwapDivCcysCount;
	}
	public ImpactedSwapDivCcy[] getimpactedSwapDivCcysArray() { 
		return _impactedSwapDivCcys;
	}
	public void setimpactedSwapDivCcysArray(ImpactedSwapDivCcy newValue[]) { 
		_impactedSwapDivCcys=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getimpactedSwapDivCcysIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_impactedSwapDivCcys==null) return false;
				if(last<0) {
					last = _impactedSwapDivCcys.length;
					while(--last>-1&&_impactedSwapDivCcys[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _impactedSwapDivCcys[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_impactedSwapDivCcys[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public ImpactedSwapDivCcy getimpactedSwapDivCcys(int idx) { 
		return (ImpactedSwapDivCcy)_impactedSwapDivCcys[idx];
	}
	public void setimpactedSwapDivCcys(ImpactedSwapDivCcy newValue) { 
		if(_impactedSwapDivCcys!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_impactedSwapDivCcys.length;__I_A++) {
				if(_impactedSwapDivCcys[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_impactedSwapDivCcys.length;
				ImpactedSwapDivCcy array[] = new ImpactedSwapDivCcy[__OPEN_A+10];
				System.arraycopy(_impactedSwapDivCcys,0,array,0,_impactedSwapDivCcys.length);
				_impactedSwapDivCcys = array;
			}
			_impactedSwapDivCcys[__OPEN_A] = newValue;
		}
		else {
			_impactedSwapDivCcys = new ImpactedSwapDivCcy[10];
			_impactedSwapDivCcys[0] = newValue;
		}
		_impactedSwapDivCcysCount++;
	}
	public int getlocation() {
		return _location;
	}
	public void setlocation(int newValue) {
		_location = newValue;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 2);
		if(_impactedSwapDivCcys!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _impactedSwapDivCcysCount);
			for(int __I_A=0;__I_A<_impactedSwapDivCcysCount;__I_A++) {
				daChild.setDataArray(__I_A, _impactedSwapDivCcys[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.putInt(_location);
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_impactedSwapDivCcysCount = daItem.getElements();
		if(_impactedSwapDivCcysCount>0) {
			_impactedSwapDivCcys = new ImpactedSwapDivCcy [(int)_impactedSwapDivCcysCount];
			for(int __I_A=0;__I_A<_impactedSwapDivCcysCount;__I_A++) {
				_impactedSwapDivCcys[__I_A] = new ImpactedSwapDivCcy();
				daItem.getDataArray(__I_A, daElement);
				_impactedSwapDivCcys[__I_A].readCache(daElement);
			}
		}
		in.getDataItem(sa_idx++, item);
		_location = item.getInt();
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ImpactedSwapDivCcy _impactedSwapDivCcys[] = null;
	private long _impactedSwapDivCcysCount = 0;
	private int _location;
	private DataItem item = new DataItem();
}

