// Title:        UpdateUserProfileRequest
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class UpdateUserProfileRequest implements FastCacheDVOBase  {
	public long getlayoutCount() { 
		return _layoutCount;
	}
	public Layout[] getlayoutArray() { 
		return _layout;
	}
	public void setlayoutArray(Layout newValue[]) { 
		_layout=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getlayoutIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_layout==null) return false;
				if(last<0) {
					last = _layout.length;
					while(--last>-1&&_layout[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _layout[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_layout[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public Layout getlayout(int idx) { 
		return (Layout)_layout[idx];
	}
	public void setlayout(Layout newValue) { 
		if(_layout!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_layout.length;__I_A++) {
				if(_layout[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_layout.length;
				Layout array[] = new Layout[__OPEN_A+10];
				System.arraycopy(_layout,0,array,0,_layout.length);
				_layout = array;
			}
			_layout[__OPEN_A] = newValue;
		}
		else {
			_layout = new Layout[10];
			_layout[0] = newValue;
		}
		_layoutCount++;
	}
	public int getlocation() {
		return _location;
	}
	public void setlocation(int newValue) {
		_location = newValue;
	}
	public int getuser() {
		return _user;
	}
	public void setuser(int newValue) {
		_user = newValue;
	}
	public String getname() {
		if(_name!=null) {
			return new String(_name);
		}
		else {
			return null;
		}
	}
	public void setname(String newValue) {
		_name = newValue!=null ? newValue.toCharArray() : null;
	}
	public int getdefaultLocation() {
		return _defaultLocation;
	}
	public void setdefaultLocation(int newValue) {
		_defaultLocation = newValue;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 5);
		if(_layout!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _layoutCount);
			for(int __I_A=0;__I_A<_layoutCount;__I_A++) {
				daChild.setDataArray(__I_A, _layout[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.putInt(_location);
		da.setDataItem(sa_idx++, item);
		item.putInt(_user);
		da.setDataItem(sa_idx++, item);
		item.putCharArray(_name);
		da.setDataItem(sa_idx++, item);
		item.putInt(_defaultLocation);
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_layoutCount = daItem.getElements();
		if(_layoutCount>0) {
			_layout = new Layout [(int)_layoutCount];
			for(int __I_A=0;__I_A<_layoutCount;__I_A++) {
				_layout[__I_A] = new Layout();
				daItem.getDataArray(__I_A, daElement);
				_layout[__I_A].readCache(daElement);
			}
		}
		in.getDataItem(sa_idx++, item);
		_location = item.getInt();
		in.getDataItem(sa_idx++, item);
		_user = item.getInt();
		in.getDataItem(sa_idx++, item);
		_name = item.getCharArray();
		in.getDataItem(sa_idx++, item);
		_defaultLocation = item.getInt();
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private Layout _layout[] = null;
	private long _layoutCount = 0;
	private int _location;
	private int _user;
	private char[] _name;
	private int _defaultLocation;
	private DataItem item = new DataItem();
}

