// Title:        UploadAdjustmentResponse
// Author:       Generate code
// Company:      
// Description:  This class was generated by the XML-Broker Developer Console
// Schema name:  /home/anthony/workspace/SynthesisWS/schema/Synthesis.xsd
// Java SDK:     

package com.db.ess.synthesis.dvo;

import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;

import org.adaptinet.sdk.adaptinetex.FastCacheException;
import org.adaptinet.sdk.fastcache.CacheServer;
import org.adaptinet.sdk.fastcache.DataArray;
import org.adaptinet.sdk.fastcache.DataItem;
import org.adaptinet.sdk.fastcache.FastCacheDVOBase;

public class UploadAdjustmentResponse implements FastCacheDVOBase  {
	public ReturnResponse getreturnResponse() { 
		return _returnResponse;
	}
	public void setreturnResponse(ReturnResponse newValue) { 
		_returnResponse = newValue;
	}
	public long getadjustmentsCount() { 
		return _adjustmentsCount;
	}
	public Adjustment[] getadjustmentsArray() { 
		return _adjustments;
	}
	public void setadjustmentsArray(Adjustment newValue[]) { 
		_adjustments=newValue;
	}
	@SuppressWarnings("rawtypes")
	public Iterator getadjustmentsIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_adjustments==null) return false;
				if(last<0) {
					last = _adjustments.length;
					while(--last>-1&&_adjustments[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _adjustments[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_adjustments[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public Adjustment getadjustments(int idx) { 
		return (Adjustment)_adjustments[idx];
	}
	public void setadjustments(Adjustment newValue) { 
		if(_adjustments!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_adjustments.length;__I_A++) {
				if(_adjustments[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_adjustments.length;
				Adjustment array[] = new Adjustment[__OPEN_A+10];
				System.arraycopy(_adjustments,0,array,0,_adjustments.length);
				_adjustments = array;
			}
			_adjustments[__OPEN_A] = newValue;
		}
		else {
			_adjustments = new Adjustment[10];
			_adjustments[0] = newValue;
		}
		_adjustmentsCount++;
	}
	public boolean getisUploadSuccess() {
		return _isUploadSuccess;
	}
	public void setisUploadSuccess(boolean newValue) {
		_isUploadSuccess = newValue;
	}
	public void putToCache(String key, CacheServer server) throws FastCacheException {
		DataArray da = writeCache();
		item.putDataArray(da);
		server.putValue(key, item);
		item.DataItemClear();
	}
	public void getFromCache(String key, CacheServer server) throws FastCacheException {
		DataItem item = server.getValue(key);
		DataArray da = new DataArray();
		item.getDataArray(da);
		readCache(da);
		item.DataItemClear();
	}
	public DataArray writeCache() throws FastCacheException {
		int sa_idx = 0;
		DataArray da = new DataArray(DataItem.DATAITEMDATAITEM, 3);
		item.putDataArray(_returnResponse.writeCache());
		da.setDataItem(sa_idx++, item);
		if(_adjustments!=null) {
			DataArray daChild = new DataArray(DataItem.DATAITEMARRAY, _adjustmentsCount);
			for(int __I_A=0;__I_A<_adjustmentsCount;__I_A++) {
				daChild.setDataArray(__I_A, _adjustments[__I_A].writeCache());
			}
			item.putDataArray(daChild);
		}
		else {
			item.putEmpty();
		}
		da.setDataItem(sa_idx++, item);
		item.putBoolean(_isUploadSuccess);
		da.setDataItem(sa_idx++, item);
		item.DataItemClear();
		return da;
	}
	public void readCache(DataArray in) throws FastCacheException {
		int sa_idx = 0;
		DataArray daItem = new DataArray();
		DataArray daElement = new DataArray();
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_returnResponse.readCache(daItem);
		in.getDataItem(sa_idx++, item);
		item.getDataArray(daItem);
		_adjustmentsCount = daItem.getElements();
		if(_adjustmentsCount>0) {
			_adjustments = new Adjustment [(int)_adjustmentsCount];
			for(int __I_A=0;__I_A<_adjustmentsCount;__I_A++) {
				_adjustments[__I_A] = new Adjustment();
				daItem.getDataArray(__I_A, daElement);
				_adjustments[__I_A].readCache(daElement);
			}
		}
		in.getDataItem(sa_idx++, item);
		_isUploadSuccess = item.getBoolean();
	}
	public void writeObject(byte [] data) throws FastCacheException {
		item.writeObject(data);
		DataArray in = new DataArray();
		item.getDataArray(in);
		readCache(in);
	}
	public byte [] readObject() throws FastCacheException, IOException {
		DataArray requestDA = writeCache();
		item.putDataArray(requestDA);
		return item.readObject();
	}
	private ReturnResponse _returnResponse =  new ReturnResponse();
	private Adjustment _adjustments[] = null;
	private long _adjustmentsCount = 0;
	private boolean _isUploadSuccess;
	private DataItem item = new DataItem();
}

